### PR TITLE
Add bluge v0.2.2

### LINKED ISSUE #36: Add bluge to the benchmark
See [github project](https://github.com/blugelabs/bluge)

### PR DESCRIPTION
**Pull request by k-yomo**
Resolves #36 

#### 📝 NOTE
- bluge doesn't support count only query
- bluge doesn't support force merge

### CODE REVIEW

**Comment by fulmicoton** [comment]
Indexing works. Merge does not (we can live without it if necessary). Search does not work yet..

**Comment by k-yomo** [comment]
@fulmicoton 
Excuse me for leaving this PR for a long time.
I think it's ready for review, could you take a look when you have time?🙏

**Comment by fulmicoton** [comment]
thank you k-yomo.
we will have a look

**Comment by fulmicoton** [comment]
@k-yomo It ran fine on my computer. Thank you

**Pull request merged**
